service: lambdaChromePuptr

custom:
  scrnshotsBucket: lambda.chrome.puptr.screenshots

provider:
  name: aws
  region: us-east-1
  versionFunctions: false
  runtime: nodejs12.x
  memorySize: 2048
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: arn:aws:s3:::${self:custom.scrnshotsBucket}/*
  
functions:
  takescreenshot:
    handler: src/index.handler
    layers:
      - arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:10
    environment:
      S3_REGION: ${self:provider.region}
      S3_BUCKET: ${self:custom.scrnshotsBucket}

resources:
  Resources:
    screenshotsBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Delete
      Properties:
        BucketName: ${self:custom.scrnshotsBucket}
        AccessControl: Private
    screenshotsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Principal: "*"
              Resource: arn:aws:s3:::${self:custom.scrnshotsBucket}/*
        Bucket:
          Ref: screenshotsBucket